### Стенд для локальной разработки
version: '3.9'
name: meteoStation
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_MAX_CONNECTIONS: 1000
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgsql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "6134:5432"
