name: reusable-deploy

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      make_command:
        required: true
        type: string
      devops_repository:
        required: true
        type: string

env:
  REGISTRY: ghcr.io

jobs:

  # Собираем и пушим Docker-образ
  docker-build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Extract version from ref
        run: |
          echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "BUILD_DATE=$(git log -1 --format=%cd --date=short)" >> $GITHUB_ENV

        # Логинимся в Container registry
      - name: Login to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

        # Скачиваем все подмодули
      - name: Download submodules
        run: |
          git submodule update --init --recursive

        # Собираем и пушим Docker-образ
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: build/Dockerfile
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ inputs.image_name }}:${{ env.VERSION }}
            ${{ env.REGISTRY }}/${{ inputs.image_name }}:latest
            ${{ env.REGISTRY }}/${{ inputs.image_name }}:build-${{ github.run_id }}
          build-args: |
            CI_JOB_TOKEN=${{ secrets.PAT_TOKEN }}
            VERSION=${{ env.VERSION }}
            BUILD=${{ github.run_id }}
            BUILD_DATE=${{ env.BUILD_DATE }}

#  # Деплой через Ansible
#  ansible-deploy:
#    needs: docker-build-and-push
#    runs-on: ubuntu-latest
#    container:
#      image: willhallonline/ansible:latest
#    steps:
#      # Переключаемся в devops репозиторий
#      - uses: actions/checkout@v4
#        with:
#          repository: ${{ inputs.devops_repository }}
#          token: '${{ secrets.PAT_TOKEN }}'
#
#        # Настраиваем ssh
#      - name: Setup SSH
#        run: |
#          mkdir -p ~/.ssh
#          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa_github
#          chmod 600 ~/.ssh/id_rsa_github
#
#      - name: Install Make
#        run: |
#          apk update && apk add make
#
#      # Создаем файл с паролем для Ansible Vault
#      - name: Make file with vault password
#        run: |
#          VAULT_PASSWORD=${{ secrets.VAULT_PASSWORD }} make add-ansible-vault-password
#
#
#        # Устанавливаем переменные окружения
#      - name: Run Ansible playbook
#        run: |
#          ANSIBLE_HOST_KEY_CHECKING=False make ${{ inputs.make_command }}
